/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package application;

import controllers.GeneracionJpaController;
import controllers.PokemonJpaController;
import controllers.exceptions.NonexistentEntityException;
import entities.Generacion;
import entities.Pokemon;
import java.math.BigDecimal;
import java.time.DateTimeException;
import java.time.Instant;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Juan Diego
 */
public class FrameGeneracionUpdate extends javax.swing.JFrame {

    /**
     * Creates new form FrameModificar
     */
    public FrameGeneracionUpdate() {
        initComponents();
        listaGen.setEnabled(false);

        this.textoError.setVisible(false);
        this.textoVacio.setVisible(false);

        this.nombreGen.setVisible(false);
        this.nombreGenTexto.setVisible(false);

        this.numeroPokemons.setVisible(false);
        this.numeroPokemonsTexto.setVisible(false);

        this.numeroRegion.setVisible(false);
        this.numeroRegionTexto.setVisible(false);

        this.botonModificar.setVisible(false);

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("pokemon");
        GeneracionJpaController gc = new GeneracionJpaController(emf);

        List<Generacion> gens = gc.findGeneracionEntities();

        DefaultTableModel m = new DefaultTableModel();

        m.setColumnIdentifiers(new String[]{" Generacion ID ", " Numero Generacion ", " Numero de Pokemon ", " Nombre Generacion "});
        for (Generacion g : gens) {

            Object[] objetos = {g.getIdGeneracion(), g.getNumeroGeneracion(), g.getNumeroPokemon(), g.getNombreRegion()};
            m.addRow(objetos);
        }

        listaGen.setModel(m);
        listaGen.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textoCodigo = new javax.swing.JLabel();
        Codigo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaGen = new javax.swing.JTable();
        Atras = new javax.swing.JButton();
        OkeyBotton = new javax.swing.JButton();
        botonModificar = new javax.swing.JButton();
        textoError = new javax.swing.JLabel();
        textoVacio = new javax.swing.JLabel();
        nombreGen = new javax.swing.JLabel();
        nombreGenTexto = new javax.swing.JTextField();
        numeroRegion = new javax.swing.JLabel();
        numeroRegionTexto = new javax.swing.JTextField();
        numeroPokemons = new javax.swing.JLabel();
        numeroPokemonsTexto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textoCodigo.setText("Introduce el id de la generacion que quieras modificar");

        listaGen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(listaGen);

        Atras.setText("Volver");
        Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasActionPerformed(evt);
            }
        });

        OkeyBotton.setText("Ok");
        OkeyBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkeyBottonActionPerformed(evt);
            }
        });

        botonModificar.setText("Modificar");
        botonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarActionPerformed(evt);
            }
        });

        textoError.setText("Esa generacion no esxiste , vuelva a introducir el id");

        textoVacio.setText("Inserta al menos un dato para modificar la generacion");

        nombreGen.setText("Nombre");

        nombreGenTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreGenTextoActionPerformed(evt);
            }
        });

        numeroRegion.setText("Numero Region");

        numeroPokemons.setText("Numero de pokemon");

        numeroPokemonsTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroPokemonsTextoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(textoVacio)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(textoCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textoError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(31, 31, 31)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(OkeyBotton, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addComponent(Codigo, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(numeroPokemons)
                        .addGap(18, 18, 18)
                        .addComponent(numeroPokemonsTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreGen)
                            .addComponent(numeroRegion))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(botonModificar)
                                .addGap(85, 85, 85)
                                .addComponent(Atras, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombreGenTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numeroRegionTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoCodigo)
                    .addComponent(Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OkeyBotton)
                    .addComponent(textoError))
                .addGap(18, 18, 18)
                .addComponent(textoVacio)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreGen)
                    .addComponent(nombreGenTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroRegion)
                    .addComponent(numeroRegionTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroPokemons)
                    .addComponent(numeroPokemonsTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Atras)
                    .addComponent(botonModificar))
                .addGap(50, 50, 50))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasActionPerformed
        // TODO add your handling code here:

        FrameGeneracion fm= new FrameGeneracion();
        fm.setVisible(true);
        System.out.println(fm);
        this.dispose();
    }//GEN-LAST:event_AtrasActionPerformed

    private void OkeyBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkeyBottonActionPerformed
        // TODO add your handling code here:

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("pokemon");

       GeneracionJpaController gc = new GeneracionJpaController(emf);

        String pk = Codigo.getText();
        int key = 0;
        try {
            key = Integer.parseInt(pk);
            this.textoError.setVisible(false);
        } catch (NumberFormatException nfe) {
            this.textoError.setVisible(true);
        }

        boolean seguir = false;
        List<Generacion> gens = gc.findGeneracionEntities();

        for (Generacion g : gens) {

            if (g.getIdGeneracion() == key) {
                seguir = true;
            }

        }

        if (seguir) {
            this.nombreGen.setVisible(true);
            this.nombreGenTexto.setVisible(true);

            this.numeroPokemons.setVisible(true);
            this.numeroPokemonsTexto.setVisible(true);

            this.numeroRegion.setVisible(true);
            this.numeroRegionTexto.setVisible(true);

            this.botonModificar.setVisible(true);
        } else {
            this.textoError.setVisible(true);

            this.nombreGen.setVisible(false);
            this.nombreGenTexto.setVisible(false);

            this.numeroPokemons.setVisible(false);
            this.numeroPokemonsTexto.setVisible(false);

            this.numeroRegion.setVisible(false);
            this.numeroRegionTexto.setVisible(false);

            this.botonModificar.setVisible(false);
        }
    }//GEN-LAST:event_OkeyBottonActionPerformed

    private void botonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarActionPerformed

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("pokemon");

        GeneracionJpaController gc = new GeneracionJpaController(emf);

        int pk = Integer.parseInt(this.Codigo.getText());

        Generacion aux = gc.findGeneracion(pk);

        if (nombreGenTexto.getText().equals("")
                && numeroPokemonsTexto.getText().equals("")
                && numeroRegionTexto.getText().equals("")) {

            this.textoVacio.setVisible(true);

        } else {

            if (nombreGenTexto.getText().equals("")) {

                aux.setNombreRegion(aux.getNombreRegion());

            } else {

                aux.setNombreRegion(nombreGenTexto.getText());

            }

            if (numeroPokemonsTexto.getText().equals("")) {

                aux.setNumeroPokemon(aux.getNumeroPokemon());

            } else {

                try {
                    aux.setNumeroPokemon(Integer.parseInt(numeroPokemonsTexto.getText()));
                } catch (NumberFormatException e) {
                }

            }

            if (numeroRegionTexto.getText().equals("")) {

                aux.setNumeroGeneracion(aux.getNumeroGeneracion());

            } else {

                try {
                    aux.setNumeroGeneracion(Integer.parseInt(numeroRegionTexto.getText()));
                } catch (NumberFormatException e) {
                }

            }

            try {
                gc.edit(aux);
            } catch (NonexistentEntityException ex) {
                Logger.getLogger(FrameGeneracionUpdate.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(FrameGeneracionUpdate.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

        List<Generacion> gens = gc.findGeneracionEntities();

        DefaultTableModel m = new DefaultTableModel();

        m.setColumnIdentifiers(new String[]{" Generacion ID ", " Numero Generacion ", " Numero de Pokemon ", " Nombre Generacion "});
        for (Generacion g : gens) {

            Object[] objetos = {g.getIdGeneracion(), g.getNumeroGeneracion(), g.getNumeroPokemon(), g.getNombreRegion()};
            m.addRow(objetos);
        }

        listaGen.setModel(m);
        listaGen.setVisible(true);

    }//GEN-LAST:event_botonModificarActionPerformed

    private void numeroPokemonsTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroPokemonsTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroPokemonsTextoActionPerformed

    private void nombreGenTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreGenTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreGenTextoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameGeneracionUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameGeneracionUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameGeneracionUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameGeneracionUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameGeneracionUpdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras;
    private javax.swing.JTextField Codigo;
    private javax.swing.JButton OkeyBotton;
    private javax.swing.JButton botonModificar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listaGen;
    private javax.swing.JLabel nombreGen;
    private javax.swing.JTextField nombreGenTexto;
    private javax.swing.JLabel numeroPokemons;
    private javax.swing.JTextField numeroPokemonsTexto;
    private javax.swing.JLabel numeroRegion;
    private javax.swing.JTextField numeroRegionTexto;
    private javax.swing.JLabel textoCodigo;
    private javax.swing.JLabel textoError;
    private javax.swing.JLabel textoVacio;
    // End of variables declaration//GEN-END:variables
}
